# docker-compose.yml (開発環境用)
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: weight-management-app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - weight-app-network

  # 将来的にバックエンドが必要になった場合用（現在はコメントアウト）
  # api:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   container_name: weight-management-api
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./api:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #   networks:
  #     - weight-app-network

networks:
  weight-app-network:
    driver: bridge

volumes:
  node_modules: